[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
bright_foreground = "#f2e5bc"
dim_foreground = "#f9f5d7"
foreground = "#ebdbb2"

[colors.search.focused_match]
background = "#f37736"
foreground = "#000000"

[colors.search.matches]
background = "#ffc425"
foreground = "#000000"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor]
blink_interval = 750
blink_timeout = 0
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[debug]
log_level = "Error"
persistent_logging = true

[env]
TERM = "alacritty"

[font]
size = 10.0

[font.bold]
family = "FiraMono Nerd Font"
style = "Bold"

[font.normal]
family = "FiraMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 3
y = 5
