#!/usr/bin/perl

use strict;
use warnings;
use utf8;
my $acpi;
my $status;
my $percent;
my $output;

# get battery info
open (ACPI, "acpi -b|") or die;
$acpi = <ACPI>;
close(ACPI);

# check output
if ($acpi !~ /: (\w+), (\d+)%/) {
	die "$acpi\n";
}

# building output text
$status = $1;
$percent = $2;
$output = "";

if ($status eq 'Charging') {
	$output .= ' ';
} elsif ($percent < 10) {
    $output .= ' ';
} elsif ($percent < 30) {
    $output .= ' ';
} elsif ($percent < 60) {
    $output .= ' ';
} elsif ($percent < 85) {
    $output .= ' ';
} elsif ($percent <= 100) {
    $output .= ' ';
}

$output .= "$percent%";

print "$output\n$output\n#ffc425";
exit(0);
